2019-Echo-Team-KALI/Career-Track-Application

- app/javascript/components/App.js
- app/javascript/components/CareerMainPage.js
- app/javascript/components/pages/jobs/CreateJob.js
- app/javascript/components/pages/jobs/ShowCurrentJob.js
We finally got the CRUD functionality to work for jobs, next will be for the tasks
Note: There is still some refactoring for the Job's CRUD functionality such as doing the validation for the user
We finished with completing the update
> 1.update job functionality

- app/controllers/jobs_controller.rb
- app/controllers/tasks_controller.rb
- app/javascript/components/App.js
- app/javascript/components/CareerMainPage.js
- app/javascript/components/pages/jobs/AddTask.js
- app/javascript/components/pages/jobs/CreateJob.js
- app/javascript/components/pages/jobs/CurrentJobCard.js
- app/javascript/components/pages/jobs/ShowCurrentJob.js
- app/javascript/components/pages/tasks/tasklist/MainTaskList.js
We were able to have the jobs be shown for their specific user, and also have the tasks be shown for their specific job. 
Got the show page going for the Jobs
Have the edit and delete button functionality for the show currentJobCard
We have to create an edit page, so once the user creates their job, it directs them to the edit page so they can add in a task.
> 1.separate job edit/show pages

- app/assets/stylesheets/application.css
- app/assets/stylesheets/jobs.scss
- app/javascript/components/pages/jobs/CurrentJobCard.js
- app/javascript/components/pages/jobs/ShowCurrentJob.js
Added CSS for Current Job Page
- Updated spacing
- Added in Bootswatch Buttons for styling
- Made titles bold
> updated css for currentjobpage

- app/javascript/components/App.js
- app/javascript/components/pages/Header.js
- app/javascript/components/pages/jobs/CreateTaskPage.js
- app/javascript/components/pages/jobs/CurrentJobCard.js
- app/javascript/components/pages/tasks/EditTaskComponent.js
- app/javascript/components/pages/tasks/EditTaskPage.js
We created the edit task page and the edit task component and we created a edittaskpage so we can get the paramsJobID to be compared to the job_id when we do a map for the task page so we can edit the tasks, we created a edit task component so we can have the edit/delete functionality on the task itself so we dont need a separate page
Next we plan to go to the edittaskpage to grab/map the specific tasks for the job which is similar to what we did for the currentjobcard
> Created Edit task component and page current progress

- app/javascript/components/App.js
- app/javascript/components/CareerMainPage.js
- app/javascript/components/pages/jobs/CreateJob.js
- app/javascript/components/pages/jobs/CreateTaskPage.js
- app/javascript/components/pages/tasks/EditTaskComponent.js
Able to create a list of tasks after creating the job, create back and create task functions. Able to have the tasks created to be shown for the job card and the main job card.Once user presses done button it redirects to the jobcard.
Next is the edit/delete functionality for task component for the edit task page
> Created the create Tasks Page once a user created a Job

- app/javascript/components/CareerMainPage.js
- app/javascript/components/ProfileCard.js
- app/javascript/components/pages/tasks/EditTaskPage.js
- app/javascript/components/pages/tasks/tasklist/MainTaskList.js
Able to have the maintasklist component be be integrated with the profile card, we are able to link each task to their job card
Next is to style the profile card and finish up the task component to have delete and edit
> MainTaskList and Profile card integration

- app/javascript/components/CareerMainPage.js
- app/javascript/components/ProfileCard.js
- app/javascript/components/pages/jobs/CreateJob.js
- app/javascript/components/pages/tasks/tasklist/MainTaskList.js
added category selector to create job page. working on main task list styling in profile page
> More styling on task list and create new job form 

- app/assets/stylesheets/jobs.scss
- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/tasks.scss
- app/javascript/components/pages/jobs/CreateJob.js
- app/javascript/components/pages/jobs/CreateTaskPage.js
- app/javascript/components/pages/jobs/EditCurrentJob.js
- added styling for add task to make consistent with other forms
> styling for addtask

- app/javascript/react/App.js
- app/javascript/react/components/Header.js
- app/javascript/react/components/categories/CategoriesSection.js
- app/javascript/react/components/categories/CategoryComponent.js
- app/javascript/react/components/categories/JobCardComponent.js
- app/javascript/react/pages/CareerMainPage.js
- app/javascript/react/pages/MainCareerPage.js
- app/javascript/react/pages/jobs/CreateJobPage.js
- app/javascript/react/pages/jobs/CurrentJobPage.js
Created Components for the Main Career Page to set up for the "react-beautiful-dnd" library
We created the Categories Section Component for the DragDropContext, Category Component for it to be Droppable and the JobCardComponent for the Draggable specifically 
Next is to implement the css styling for the categories to be vertical and also got the other stylings down. After that we will get the drag-n-drop going.
> Created Components for the Main Career Page to set up for the Drag and Drop

- app/javascript/react/components/categories/CategoriesSection.js
- app/javascript/react/components/categories/CategoryComponent.js
- app/javascript/react/components/categories/JobCardComponent.js
- app/javascript/react/pages/jobs/CurrentJobPage.js
implemented with new file structure. Vertical column vs rows. next is to fix href on buttons with Links. Implement dnd.
> end of day.. implement css stuff with new file structure 

- app/javascript/packs/server_rendering.js
- app/javascript/react/pages/jobs/CreateJobPage.js
- app/models/job.rb
- app/models/task.rb
- db/migrate/20191213231126_add_categories_column_to_jobs.rb
- db/schema.rb
Added the validations for presence to the name and title of jobs and title of task to the models
Added the category column for the job on the backend
Making sure we are able to choose a category in the drop down and have it be placed in the backend. So we can map the jobs to the categories.
> Added Validation on the Backend, started on Mapping the Jobs on the Categories

- app/controllers/jobs_controller.rb
- app/javascript/react/components/categories/CategoryComponent.js
- app/javascript/react/pages/jobs/CreateJobPage.js
- app/javascript/react/pages/jobs/CurrentJobPage.js
- app/javascript/react/pages/jobs/EditJobPage.js
We got the jobs to be categorized in their sections on create and edit 
We plan to work on the flow of the app in terms of the user experience, this may change the structure of the application in a sense that we may need to create a Task Component to have the edit, delete, and checkout off capabilities.
> Able to have the jobs be shown in different categories

- app/controllers/jobs_controller.rb
- app/javascript/react/components/EditTaskComponent.js
- app/javascript/react/components/MainTaskComponent.js
- app/javascript/react/components/MainTaskList.js
- app/javascript/react/components/categories/CategoryComponent.js
- app/javascript/react/pages/jobs/CreateJobPage.js
- app/javascript/react/pages/jobs/CurrentJobPage.js
- app/javascript/react/pages/jobs/EditJobPage.js
- app/javascript/react/pages/tasks/CreateTaskPage.js
- app/javascript/react/pages/tasks/EditTaskPage.js
- package.json
- yarn.lock
Created the MainTask Component for the MainTaskList because it was needed to load the specific job for the Tasks in getting the company name
Fixed the bugs of having the title shown for the edit and create task page
Continue on improving the UI/UX(flow of our app) and having the category dropdown be shown in the JobCard for the maincareerpage
> 12/15/2019 1.0 improving user experience user interface

- app/javascript/react/App.js
- app/javascript/react/components/ProfileCard.js
- app/javascript/react/components/categories/JobCardComponent.js
- app/javascript/react/pages/MainCareerPage.js
- app/views/layouts/application.html.erb
- package.json
- yarn.lock
Added bootswatch CDN and added the styling and props for the sticky component tag
And able to switch statuses/categories on the main career page
Fix the bug of having the page reload once a status has been chosen
> Implement dropdown for jobcard and CDN for bootswatch

- app/views/layouts/application.html.erb
Added the react-datetime-picker-css to be implemented for the Heroku
> Added the react-datetime-picker-css to be implemented for the Heroku

- app/javascript/react/api/jobs/jobs-api.js
- app/javascript/react/components/categories/CategoriesSection.js
- app/javascript/react/components/categories/CategoryComponent.js
- app/javascript/react/components/categories/JobCardComponent.js
- app/javascript/react/pages/MainCareerPage.js
- app/javascript/react/pages/jobs/CreateJobPage.js
- app/javascript/react/pages/tasks/EditTaskPage.js
Able to have the page re-render once the user changes the status on the MainCareerPage
> Got the functionality going for changing the status in the MainCareerPage

- Gemfile
- Gemfile.lock
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
Added devise-bootstraped gem so that the login/signup page has styling rather than the basic default devise views.
> Bootstrap styling added to Devise login page

- app/javascript/react/components/EditTaskComponent.js
- app/javascript/react/components/ProfileCard.js
- app/javascript/react/components/categories/CategoriesSection.js
- app/javascript/react/pages/jobs/CreateJobPage.js
- app/javascript/react/pages/jobs/CurrentJobPage.js
- app/javascript/react/pages/tasks/CreateTaskPage.js
- app/javascript/react/pages/tasks/EditTaskPage.js
styling for track new listing page. reload is now add task on edit task page
> Button moving and styling 

- app/javascript/react/App.js
- app/javascript/react/pages/jobs/CreateJobPage.js
- app/javascript/react/pages/jobs/CurrentJobPage.js
- app/javascript/react/pages/tasks/CreateFirstTaskPage.js
Fixed the flow of when the user first creates a job with the tasks, and when the job has already been created and the user is trying to add and complete tasks
Fix up some confirmations for deleting jobs and tasks
> Created a separate create tasks page when the user first creates a job

- app/controllers/jobs_controller.rb
- spec/models/job_spec.rb
- spec/models/task_spec.rb
- spec/rails_helper.rb
- spec/requests/jobs_spec.rb
- spec/requests/tasks_spec.rb
Request testing for jobs complete. Tasks request testing is in progress. Some model tests for each.
> 12 17 2019 rspec model testing

- app/controllers/tasks_controller.rb
- spec/requests/tasks_spec.rb
- Completed rspec request testing for the Tasks and Jobs
> completed request testing

- app/javascript/react/pages/jobs/CurrentJobPage.js
Added the ability to conditionally render to add a url or description if the user didnt add them
> Added the ability to conditionally render to add a url or description if the user didnt add them
